### ISSUE TITLE
More explanation on how to configure plots ?

### ISSUE THREAD

**Issue by Greece2** [cattanimarco/Ardu-DataVis#19]
Hi Marco,
the examples are pretty impressive !  I read and tried them all, also looked at the wiki and the source code.
The examples are a bit complex and some comments about which parameter does what would be great !
But still, I can't figure out simple things like 
- setting boundaries (i.e. if one only wants to use a part of the display for the diagram
- how to adjust the rotation of the diagram to the screen rotation
- how to make visible X/Y-axes with names and numbers
- how to make bar graphs horizontally / vertically and how to set the colors
- how to scale the axes
- in dataset.begin(dataArray, 1 ,5), dataArry contains the data, 5 is for 5 elemets, but what is the "1" doing ?
-  
Maybe you could add some explaining comments to the examples or the wiki ?  That would be great !
Many thanks in davance !

**Comment by cattanimarco** [comment]
I agree the documentation is a bit behind and the api is not particularly clear. I will soon release a new version of Grafici which, unfortunately, will break backward compatibility. The goal is to have a library with a clearer (documented) api and simpler code. I will still try to unswer you questions in the next day. Hopefully you will be patient enough to try the new release soon

**Comment by Greece2** [comment]
Hi Marc, that's good news !
Of course, I'll be patient and wait ;-)
A good example for a documentation is found for the UCGLIB (in my opinion), well structured and a short explanation for each command. I used that style as a template for something I did a while ago (nothing connected to ARDUINO...)
Best regards + keep safe !

**Comment by cattanimarco** [comment]
It has been a while but I released Grafici 3.0 if you want to have a look

**Comment by cattanimarco** [comment]
Actually UCGLIB is quite a good library! I agree I could create the documentation bases on it and I could also use UCGLIB as the base driver for my library

**Comment by cattanimarco** [comment]
I am still working on it, please be patient

**Comment by cattanimarco** [comment]
Grafici 4.0 focused on simplify the configurations of plots and adding more useful examples. 
Hopefully no additional documentation is now required
